Rails.application.config.assets.precompile += %w( foundation-overrides.css )
Rails.application.config.assets.precompile += %w( style.css )
Rails.application.config.assets.precompile += %w( normalize.css )
Rails.application.config.assets.precompile += %w( script.js)
Rails.application.config.assets.precompile += %w( flaticon.css )
